package main

import (
	"encoding/json"
	"fmt"
	"path/filepath"

	"openflux/share"
)

// EgressSubnet is the Docker network the egress container lives on. The
// host routes this subnet around its own full-tunnel VPN (an ip rule), so
// the egress tunnels reach their servers over the plain uplink.
const EgressSubnet = "172.31.250.0/24"

// nodeConf is the exit node's .conf for c: a classic single-transport exit
// with a key. A classic exit serves both classic clients and Session
// clients; one configured with [Transport] sections serves Session clients
// only, which would lock out apps without Session support.
//
// URL is safe to write as is: validURL keeps out what the .conf parser
// would read as a comment or a line break.
func nodeConf(c Client) string {
	return fmt.Sprintf(`# Generated by reflux from client.json; do not edit.
[Interface]
Role = exit
Mode = l4
Transport = %s
URL = %s
EncryptionKeyFile = /config/key
CookieStore = /state/cookies.json
`, c.Transport, c.URL)
}

// shareConfig is what a client app needs to connect to c's node.
func shareConfig(c Client, key string) share.Config {
	return share.Config{
		Name:       "ReFlux " + c.Name,
		Secret:     key,
		Transports: []share.Transport{{Type: c.Transport, URL: c.URL}},
	}
}

// Options are the host-specific parts of compose.yml.
type Options struct {
	NodeImage   string
	EgressImage string
	// UID and GID the nodes run as: the owner of the data directory, so
	// they can read their 0600 key and write their state.
	UID, GID int
}

type composeFile struct {
	Name     string                    `json:"name"`
	Services map[string]composeService `json:"services"`
	Networks map[string]composeNetwork `json:"networks"`
	Volumes  map[string]struct{}       `json:"volumes"`
}

type composeService struct {
	Image         string                       `json:"image"`
	ContainerName string                       `json:"container_name"`
	Restart       string                       `json:"restart"`
	Entrypoint    []string                     `json:"entrypoint,omitempty"`
	Command       []string                     `json:"command,omitempty"`
	Environment   map[string]string            `json:"environment,omitempty"`
	User          string                       `json:"user,omitempty"`
	ReadOnly      bool                         `json:"read_only,omitempty"`
	Tmpfs         []string                     `json:"tmpfs,omitempty"`
	CapDrop       []string                     `json:"cap_drop,omitempty"`
	CapAdd        []string                     `json:"cap_add,omitempty"`
	SecurityOpt   []string                     `json:"security_opt,omitempty"`
	Devices       []string                     `json:"devices,omitempty"`
	Sysctls       map[string]string            `json:"sysctls,omitempty"`
	Volumes       []string                     `json:"volumes,omitempty"`
	NetworkMode   string                       `json:"network_mode,omitempty"`
	Networks      map[string]composeServiceNet `json:"networks,omitempty"`
	DependsOn     []string                     `json:"depends_on,omitempty"`
	Labels        map[string]string            `json:"labels,omitempty"`
	Logging       composeLogging               `json:"logging"`
}

type composeServiceNet struct {
	IPv4Address string `json:"ipv4_address,omitempty"`
}

type composeNetwork struct {
	Driver     string            `json:"driver"`
	DriverOpts map[string]string `json:"driver_opts,omitempty"`
	IPAM       composeIPAM       `json:"ipam"`
}

type composeIPAM struct {
	Config []map[string]string `json:"config"`
}

type composeLogging struct {
	Driver  string            `json:"driver"`
	Options map[string]string `json:"options"`
}

// noProxy blanks the proxy variables the Docker CLI copies into containers
// from ~/.docker/config.json: a node must leave through egress only, never
// through a proxy of the host's own. Empty values count as unset.
var noProxy = map[string]string{
	"HTTP_PROXY": "", "HTTPS_PROXY": "", "ALL_PROXY": "", "NO_PROXY": "",
	"http_proxy": "", "https_proxy": "", "all_proxy": "", "no_proxy": "",
}

var defaultLogging = composeLogging{
	Driver:  "json-file",
	Options: map[string]string{"max-size": "10m", "max-file": "3"},
}

// composeYAML renders compose.yml: the egress container and one exit node
// per client. Nodes have no network of their own: they share the egress
// container's, so every packet they send leaves through its tunnels (or
// not at all), never from the host's address. No service publishes a port:
// Docker's published ports bypass the host firewall, and nodes only dial
// out to their carrier.
//
// The file is JSON, which is valid YAML, so no YAML library is needed.
func composeYAML(root string, clients []Client, o Options) ([]byte, error) {
	f := composeFile{
		Name:     "reflux",
		Services: map[string]composeService{},
		Networks: map[string]composeNetwork{
			"egress": {
				Driver:     "bridge",
				DriverOpts: map[string]string{"com.docker.network.bridge.name": "reflux0"},
				IPAM:       composeIPAM{Config: []map[string]string{{"subnet": EgressSubnet}}},
			},
		},
		// The egress's cached RU prefix list.
		Volumes: map[string]struct{}{"egress-state": {}},
	}
	// The egress runs as root for netlink, but with only the capabilities
	// it needs: NET_ADMIN (tunnels, routes, nftables), NET_RAW (probes)
	// and DAC_READ_SEARCH (reading the owner's 0600 tunnel configs, never
	// writing them). IPv6 is off: the tunnels and the kill switch are IPv4.
	f.Services["egress"] = composeService{
		Image:         o.EgressImage,
		ContainerName: "reflux-egress",
		Restart:       "unless-stopped",
		CapDrop:       []string{"ALL"},
		CapAdd:        []string{"NET_ADMIN", "NET_RAW", "DAC_READ_SEARCH"},
		SecurityOpt:   []string{"no-new-privileges:true"},
		Environment:   noProxy,
		Sysctls: map[string]string{
			"net.ipv4.conf.all.src_valid_mark":   "1",
			"net.ipv6.conf.all.disable_ipv6":     "1",
			"net.ipv6.conf.default.disable_ipv6": "1",
		},
		Volumes: []string{
			filepath.Join(root, "egress") + ":/etc/reflux/egress:ro",
			"egress-state:/var/lib/reflux-egress",
		},
		Networks: map[string]composeServiceNet{"egress": {}},
		Logging:  defaultLogging,
	}
	for _, c := range clients {
		f.Services["node-"+c.Name] = composeService{
			Image:         o.NodeImage,
			ContainerName: "reflux-node-" + c.Name,
			Restart:       "unless-stopped",
			Entrypoint:    []string{"openflux"},
			Command:       []string{"--config", "/config/node.conf"},
			Environment:   noProxy,
			User:          fmt.Sprintf("%d:%d", o.UID, o.GID),
			ReadOnly:      true,
			Tmpfs:         []string{"/tmp"},
			CapDrop:       []string{"ALL"},
			SecurityOpt:   []string{"no-new-privileges:true"},
			Volumes: []string{
				filepath.Join(root, "clients", c.Name) + ":/config:ro",
				filepath.Join(root, "state", c.Name) + ":/state",
			},
			NetworkMode: "service:egress",
			DependsOn:   []string{"egress"},
			Labels:      map[string]string{"io.reflux.client": c.Name},
			Logging:     defaultLogging,
		}
	}
	b, err := json.MarshalIndent(f, "", "  ")
	if err != nil {
		return nil, err
	}
	head := "# Generated by reflux; do not edit. `reflux apply` rewrites it.\n"
	return append([]byte(head), append(b, '\n')...), nil
}
